cat <<EOF > .github/workflows/main.yml
name: VANGUARD CI - Continuous Compliance Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    name: Run Semgrep on Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep scan
        run: |
          semgrep --config=auto src/ --json > scans/semgrep-output.json
EOF
