name: VANGARD CI - Continuous Compliance Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compliance-scan:
    name: Run Semgrep, tfsec, and Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install semgrep

      - name: Run Semgrep scan
        run: |
          mkdir -p scans
          semgrep --config=p/ci src/ --json > scans/semgrep-output.json

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec scan
        run: |
          tfsec iac/ --format json > scans/tfsec-output.json

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.63.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.63.0_Linux-64bit.deb

      - name: Build Docker image
        run: docker build -t insecure-app .

      - name: Run Trivy scan
        run: |
          trivy image --format json --output scans/trivy-output.json insecure-app

      - name: Upload scan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: scans/


      - name: Upload scan results and POA&M reports
        uses: actions/upload-artifact@v4
        with:
          name: vanguard-ci-artifacts
          path: |
            scans/semgrep-output.json
            scans/tfsec-output.json
            scans/trivy-output.json
            scans/semgrep-poam-summary.csv
            scans/tfsec-poam-summary.csv
            scans/trivy-poam-summary.csv
            scans/master-poam-summary.csv
            scans/vanguard-poam-summary.png
